### ISSUE TITLE
곡 목록을 불러오면 메모리 사용량이 급격하게 상승하고, 다른 뷰로 이동해도 다시 줄어들지 않습니다.

### ISSUE THREAD

**Issue by youn9k** [billboardoo/billboardoo-ios#4]
1.
![화면 기록 2022-10-04 오후 9 55 35](https://user-images.githubusercontent.com/60254939/193825365-106b1b80-46ce-4103-bbcb-54c3d7aebcaf.gif)

2.
![화면 기록 2022-10-04 오후 9 55 35](https://user-images.githubusercontent.com/60254939/193825516-b129cff5-c406-4b09-a390-0e58cbaca5fe.gif)

3.
![화면 기록 2022-10-04 오후 9 55 35](https://user-images.githubusercontent.com/60254939/193825619-d9a6f59f-6e54-4760-bd5e-c3f5a701a6d1.gif)

4.
![화면 기록 2022-10-04 오후 9 55 35](https://user-images.githubusercontent.com/60254939/193825782-2b3c3cf3-cc61-4074-9c74-1b50094b6cc8.gif)

**Comment by ebPark9511** [comment]
-> 곡 목록을 불러오면 메모리 사용량 급격하게 상승 
ImageView 프레임보다 훨씬 큰 이미지를 랜더링 하려다보니 메모리가 과하게 튀는것으로 보입니다.


```Swift
            KFImage(URL(string: song.image.convertFullThumbNailImageUrl()))
                .placeholder({
                    Image("placeHolder")
                        .resizable()
                        .frame(width: 45, height: 45)
                        .transition(.opacity.combined(with: .scale))
                })
// 킹피셔 다운샘플링
                .downsampling(size: CGSize(width: 135, height: 135)) // 3배수
                .resizable()

```

테스트:
![화면_기록_2022-10-06_오후_10_33_43_AdobeExpress (1)](https://user-images.githubusercontent.com/33455020/194327976-0477787f-5797-42a4-acf9-501d629055dd.gif)

**Comment by youn9k** [comment]
#11
