### ISSUE TITLE
MusicCart를 통해 곡 재생/추가 했을 때, 다음 곡 재생 시 의도와 다른 곡이 재생됩니다.

### ISSUE THREAD

**Issue by youn9k** [billboardoo/billboardoo-ios#41]
https://user-images.githubusercontent.com/60254939/201088976-755edf4c-cc65-4a60-af99-4ef8aa60bed5.mov

**Comment by youn9k** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/60254939/201089240-745ac59a-de3f-4b5f-b107-ea02c232d755.png">

playState.playList.currentPlayIndex 를 변경해주는 곳이 없어서 그런듯

**Comment by yongbeomkwak** [comment]
만약 리스트에 값이 존재할 때 해당 인덱스로 변경하면 될듯 .firstIndex 함수 이용해서??
